services:
  bot:
    image: ghcr.io/redarek/go-tg-bot-rest:latest
    container_name: telegram_bot
    restart: always
    depends_on:
      - db
    env_file: .env

  db:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
